### ISSUE TITLE
add support for shorthand npx command

### ISSUE THREAD

**Issue by iambumblehead** [jeanbmar/s3-sync-client#24]
I'm interested to try using this package in my CI setup,

currently my setup uses [s3-directory-sync-cli][0] and [s3-invalidate-cloudfront-id][1] in this sort of way, where env vars are defined and then the npm package is called,
```bash
S3_DIRECTORY_SYNC_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
S3_DIRECTORY_SYNC_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
S3_DIRECTORY_SYNC_BUCKET=$AWS_BUCKET_NAME \
S3_DIRECTORY_SYNC_LOCAL_DIRECTORY=build \
S3_DIRECTORY_SYNC_DRIVE_CONTENT_TYPE="true" \
npx @foo-software/s3-directory-sync-cli
S3_INVALIDATE_CLOUDFRONT_REGION=eu-central-1 \
S3_INVALIDATE_CLOUDFRONT_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
S3_INVALIDATE_CLOUDFRONT_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
S3_INVALIDATE_CLOUDFRONT_IDS=E29BKF76GZ5 \
npx s3-invalidate-cloudfront-id
```

Using npx this way allows me to use these packages in CI pipelines without updating my package.json or adding config files. npx uses [the 'bin' namespace][2] to define an entry point.

Would s3-sync-client add support for npx usage?

-----------------------------
Does s3-sync-client support compression in any way? A similar package [added support for GZIP compression here.][3]

Thanks!

[0]: https://github.com/foo-software/s3-directory-sync-cli
[1]: https://github.com/iambumblehead/s3-invalidate-cloudfront-id
[2]: https://github.com/iambumblehead/s3-invalidate-cloudfront-id/blob/main/package.json#L11-L13
[3]: https://github.com/multiplegeorges/vue-cli-plugin-s3-deploy/pull/51/files

**Comment by jeanbmar** [comment]
Hello there,

#### First, about a CLI wrapper (e.g. `npx` usage)
I understand the use case but I'm not a fan of supporting it _natively_ for two reasons:
- Using this module as a CLI would be an edge case since https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html already exists. I understand you can't use the official CLI in CI but that would remain an edge case for this module.
- It's too much work to do for an edge case. Wrapping advanced options such as https://github.com/jeanbmar/s3-sync-client#use-aws-sdk-command-input-options would require additional dependencies and logic that exceed the purpose of syncing objects.

If I was in your situation I would write the CLI wrapper around this module myself, with a subset of options tailored to my requirements, like you did in s3-invalidate-cloudfront-id.

#### Then, about the compression requirements
My understanding is that you want to store gzipped files in S3 so they can be served compressed without further processing by your website.
This module can't do file compression. It would imply to:
- Compress files before everything for progress tracking
- Compute ContentLength and ContentEncoding
- Doing object diff on local uncompressed files and remote compressed files before doing syncing.
I believe it drifts too much from the purpose of syncing.

In this situation I would manage compression before using the sync module.

Overall, I'm not sure you need a sync tool. It looks like you need instead an upload / deploy tool.
Have you considered using the official https://github.com/aws/aws-sdk-js-v3/tree/main/lib/lib-storage?
There's no CLI either but it would be easier to manage file compression since data go in only one direction.

**Comment by iambumblehead** [comment]
thanks for you reply @jeanbmar I will consider those points
